title: Liminal Horror
permalink: pretty
remote_theme: pmarsceill/just-the-docs
site.url: https://liminalhorrorrpg.com
logo:
color_scheme: light
encoding: UTF-8
plugins:
  - jekyll-redirect-from
include:
  - js

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

# External navigation links
nav_external_links:
  - title: Liminal Horror Library
    url: https://liminalhorrorlibrary.com/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Discord Server
    url: https://discord.gg/ptHUNSVDrJ
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Newsletter
    url: https://goblinarchives.substack.com/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Liminal Horror is developed by Gobin Archives, Josh Domanski, and Zach Hazard Vaupen"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-198234886-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)
